version : '3'
 
services:
  footballclubs:
    image: footballclubs
    ports:
      - 8082:8080
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://*:8080
    networks:
      - dotnetcorepromgrafana

  prometheus:
    image: prom/prometheus
    restart: always
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    networks:
      - dotnetcorepromgrafana

  grafana: 
    image: grafana/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    restart: always
    ports:
      - 3000:3000
    networks:
      - dotnetcorepromgrafana

networks:
  dotnetcorepromgrafana: