global:
  scrape_interval:     5s # By default, scrape targets every 5 seconds.

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
    - targets: ['localhost:9090']
  - job_name: 'salesapp-read-prometheus'
    static_configs:
    - targets: ['salesapp:8080']