{
 "title": "My First Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Tempo de Resposta",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "accMS2" } },
   "yaxes": [
    { "format": "accMS2" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.9, rate(sales_histogram_api_bucket[1m]))",
     "legendFormat": "90%"
    },
    {
     "expr": "histogram_quantile(0.5, rate(sales_histogram_api_bucket[1m]))",
     "legendFormat": "50%"
    },
    {
     "expr": "histogram_quantile(0.1, rate(sales_histogram_api_bucket[1m]))",
     "legendFormat": "10%"
    }
   ]
  },
  {
   "title": "Usuários Online",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "sales_gauge_api" }
   ]
  },
  {
   "title": "Quantidade de Vendas",
   "type": "stat",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "rate(sales_counter_api[1m])" }
   ]
  }
 ]
}